name: "СРПСКИ ПРАВНИЧКИ КЛУБ"
description: Српски правнички клуб СПК је основан ...
author: Српски правнички клуб СПК
url: http://srpskipravnickiklub.rs
markdown: redcarpet
pygments: true
permalink: pretty
paginate: 5
paginate_path: "clanci/page:num"
